min-players: 2
max-players: 10
countdown-duration: 15
team-select-time: 10
time-limit: 300
restart-delay: 5

allowed-drops:
- 297

spawn:
  world: lobby
  x: 0.5
  y: 65
  z: 0.5

signs:
- map: Spring
  join:
    x: -2
    y: 67
    z: -4
  status:
    x: -2
    y: 66
    z: -4

game-world: games

maps:
  Spring:
    schematic: Spring.schematic
    lobby:
        x: 4
        y: 1
        z: 4
        yaw: 180
    spawns:
      rangers:
        x: 6.5
        y: 12
        z: 27.5
        yaw: -90
      bandits:
        x: 97.5
        y: 12
        z: 29.5
        yaw: 90
      spectators:
        x: 48
        y: 20
        z: 45
        yaw: 180
    chests:
      rangers:
        x: 6
        y: 11
        z: 30
      bandits:
        x: 96
        y: 11
        z: 30
