game-world: games
spawn:
  world: lobby
  x: 0.5
  y: 65
  z: 0.5
allowed-drops:
- 297
signs:
- x: 0
  y: 65
  z: 2
  map: Rangers
game-lobby:
  schematic: Lobby.schematic
  spawn:
    x: 5
    y: 1
    z: 5
maps:
  Rangers:
    schematic: Rangers.schematic
    spawns:
      rangers:
        x: 25
        y: 10
        z: 10
      bandits:
        x: 25
        y: 10
        z: 90
    chests:
      rangers:
        x: 25
        y: 10
        z: 5
      bandits:
        x: 25
        y: 10
        z: 90